# Generated by Django 6.0 on 2025-12-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
