# Generated by Django 6.0 on 2025-12-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True, help_text="Telegram chat id для уведомлений", null=True
            ),
        ),
    ]
