# Generated by Django 6.0 on 2025-12-28 13:19

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_telegram_chat_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_chat_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
